<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estado de Orden - TechService Pro</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-tech-light-gray font-sans">
    
    <!-- Navigation Header -->
    <nav class="bg-tech-dark-blue shadow-lg">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex justify-between h-16">
                <div class="flex items-center">
                    <a href="{{ route('home') }}" class="flex-shrink-0">
                        <span class="text-tech-pure-white text-2xl font-bold">TechService Pro</span>
                    </a>
                </div>
                <div class="flex items-center">
                    <a href="{{ route('home') }}" class="text-tech-pure-white hover:text-tech-electric-blue px-3 py-2 rounded-md text-sm font-medium transition-colors duration-300">
                        ← Volver al inicio
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div class="bg-tech-pure-white rounded-lg shadow-lg p-8 animate-fade-in">
            <div class="text-center mb-8">
                <h1 class="text-3xl font-bold text-tech-dark-blue mb-4">Estado de Orden</h1>
                <p class="text-lg text-gray-600">Consulta el estado actual de tu orden de servicio</p>
            </div>

            <!-- Search Form -->
            <div class="mb-8">
                <form action="{{ route('ordenes.buscar') }}" method="GET" class="max-w-md mx-auto">
                    <div class="flex">
                        <input type="text" name="numero_orden" value="{{ request('numero_orden') }}" 
                               placeholder="Número de orden (ej: TS-2025-001)"
                               class="flex-1 px-4 py-2 border border-gray-300 rounded-l-lg focus:ring-2 focus:ring-tech-electric-blue focus:border-transparent transition-all duration-300">
                        <button type="submit" 
                                class="bg-tech-electric-blue hover:bg-blue-600 text-tech-pure-white px-6 py-2 rounded-r-lg font-semibold transition-all duration-300">
                            Buscar
                        </button>
                    </div>
                </form>
            </div>

            @if(isset($numeroOrden))
                <!-- Order Status Display -->
                <div id="order-status" class="animate-slide-up">
                    <div class="bg-tech-light-gray rounded-lg p-6 mb-6">
                        <div class="flex items-center justify-between mb-4">
                            <h2 class="text-xl font-semibold text-tech-dark-blue">Orden: {{ $numeroOrden }}</h2>
                            <div id="status-badge" class="px-4 py-2 rounded-full text-sm font-semibold">
                                <!-- Status will be loaded by JavaScript -->
                            </div>
                        </div>
                        
                        <div id="order-details" class="space-y-4">
                            <!-- Details will be loaded by JavaScript -->
                        </div>
                    </div>

                    <!-- Status Timeline -->
                    <div class="bg-tech-light-gray rounded-lg p-6">
                        <h3 class="text-lg font-semibold text-tech-dark-blue mb-6">Progreso del Servicio</h3>
                        <div class="relative">
                            <!-- Timeline items will be generated by JavaScript -->
                            <div id="timeline" class="space-y-6">
                                <!-- Timeline content will be inserted here -->
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Loading State -->
                <div id="loading" class="text-center py-8">
                    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-tech-electric-blue mx-auto mb-4"></div>
                    <p class="text-gray-600">Consultando estado de la orden...</p>
                </div>

                <!-- Error State -->
                <div id="error" class="hidden bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-lg animate-scale-in">
                    <div class="flex items-center">
                        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z"></path>
                        </svg>
                        <span id="error-message">Orden no encontrada. Verifica el número e intenta nuevamente.</span>
                    </div>
                </div>
            @endif
        </div>
    </div>

    <script>
        @if(isset($numeroOrden))
        // Load order status when page loads
        document.addEventListener('DOMContentLoaded', function() {
            loadOrderStatus('{{ $numeroOrden }}');
        });

        function loadOrderStatus(orderNumber) {
            fetch(`/api/orden-estado/${orderNumber}`)
                .then(response => response.json())
                .then(data => {
                    document.getElementById('loading').style.display = 'none';
                    
                    if (data.error) {
                        document.getElementById('error').style.display = 'block';
                        return;
                    }

                    // Show order status
                    document.getElementById('order-status').style.display = 'block';
                    
                    // Update status badge
                    const statusBadge = document.getElementById('status-badge');
                    const statusColors = {
                        'Recibido': 'bg-blue-100 text-blue-800',
                        'En progreso': 'bg-tech-warning-orange text-tech-pure-white',
                        'Completado': 'bg-tech-success-green text-tech-pure-white',
                        'Entregado': 'bg-gray-100 text-gray-800'
                    };
                    statusBadge.className = `px-4 py-2 rounded-full text-sm font-semibold ${statusColors[data.estado] || 'bg-gray-100 text-gray-800'}`;
                    statusBadge.textContent = data.estado;

                    // Update order details
                    const orderDetails = document.getElementById('order-details');
                    orderDetails.innerHTML = `
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <span class="font-medium text-tech-dark-blue">Estado:</span>
                                <span class="text-gray-600">${data.estado}</span>
                            </div>
                            <div>
                                <span class="font-medium text-tech-dark-blue">Fecha de Ingreso:</span>
                                <span class="text-gray-600">${data.fecha_ingreso}</span>
                            </div>
                            ${data.fecha_estimada ? `
                            <div>
                                <span class="font-medium text-tech-dark-blue">Fecha Estimada:</span>
                                <span class="text-gray-600">${data.fecha_estimada}</span>
                            </div>
                            ` : ''}
                            ${data.fecha_completado ? `
                            <div>
                                <span class="font-medium text-tech-dark-blue">Fecha Completado:</span>
                                <span class="text-gray-600">${data.fecha_completado}</span>
                            </div>
                            ` : ''}
                        </div>
                        <div class="mt-4">
                            <span class="font-medium text-tech-dark-blue">Descripción:</span>
                            <p class="text-gray-600 mt-1">${data.descripcion}</p>
                        </div>
                    `;

                    // Update timeline
                    updateTimeline(data);
                })
                .catch(error => {
                    document.getElementById('loading').style.display = 'none';
                    document.getElementById('error').style.display = 'block';
                });
        }

        function updateTimeline(data) {
            const timeline = document.getElementById('timeline');
            const timelineSteps = [
                { step: 'Recibido', description: 'Orden recibida y registrada', completed: true },
                { step: 'En progreso', description: 'Diagnóstico y reparación en curso', completed: data.estado !== 'Recibido' },
                { step: 'Completado', description: 'Reparación terminada, listo para retirar', completed: data.estado === 'Completado' || data.estado === 'Entregado' },
                { step: 'Entregado', description: 'Equipo entregado al cliente', completed: data.estado === 'Entregado' }
            ];

            timeline.innerHTML = timelineSteps.map((item, index) => `
                <div class="flex items-center">
                    <div class="flex-shrink-0 w-8 h-8 ${item.completed ? 'bg-tech-success-green' : 'bg-gray-300'} rounded-full flex items-center justify-center transition-all duration-300">
                        ${item.completed ? 
                            '<svg class="w-4 h-4 text-tech-pure-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>' : 
                            `<span class="text-xs font-semibold text-gray-600">${index + 1}</span>`
                        }
                    </div>
                    <div class="ml-4 flex-1">
                        <h4 class="text-sm font-semibold ${item.completed ? 'text-tech-dark-blue' : 'text-gray-500'}">${item.step}</h4>
                        <p class="text-sm text-gray-600">${item.description}</p>
                    </div>
                </div>
            `).join('');
        }
        @endif
    </script>
</body>
</html>